version: '3.8'

services:
  mysql:
    image: mysql:8.2.0
    environment:
      - 'MYSQL_DATABASE=ais'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=ais'
      - 'MYSQL_PASSWORD=ais'
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./csv:/var/lib/mysql-files/csv
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s #default is 30s
      timeout: 5s   #default is 30s
      retries: 5    #default is 3

  grafana:
    image: grafana/grafana
    environment:
      - 'GF_SECURITY_ADMIN_USER=ais'
      - 'GF_SECURITY_ADMIN_PASSWORD=ais'
      - 'GF_DATABASE_HOST=mysql:3306'
      - 'GF_DATABASE_NAME=ais'
      - 'GF_DATABASE_USER=ais'
      - 'GF_DATABASE_PASSWORD=ais'
      - 'GF_DATABASE_TYPE=mysql'
      - 'GF_DATABASE_MAX_OPEN_CONN=300'
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy